reste service et kill

diff --git a/inception/Makefile b/inception/Makefile
--- a/inception/Makefile
+++ b/inception/Makefile
@@ -6,7 +6,7 @@
 #    By: aduvilla <aduvilla@student.42.fr>          +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/09/23 22:29:59 by aduvilla          #+#    #+#              #
-#    Updated: 2025/04/04 15:26:38 by aduvilla         ###   ########.fr        #
+#    Updated: 2025/04/05 14:49:43 by aduvilla         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -14,39 +14,52 @@ ENV_FILE	= srcs/.env
 
 TEMP_ENV	= srcs/.env.bak
 
+DC_FILE		= ./srcs/docker-compose.yml
+
 CREDENTIALS	= secrets/credentials.txt \
 			  secrets/db_user_pwd.txt \
 			  secrets/db_root_pwd.txt \
 			  secrets/wp_admin_pwd.txt \
 			  secrets/wp_user_pwd.txt \
+			  secrets/redis_pwd.txt \
 			  secrets/ftp_pwd.txt
 
 all			: up
 
 up		:
 	@cat $(CREDENTIALS) >> $(ENV_FILE)
-	@mkdir -p ~/data/mariadb ~/data/wordpress ~/data/portainer
+	@mkdir -p ~/data/mariadb ~/data/wordpress
 	docker compose -f ./srcs/docker-compose.yml up -d
 	@cat $(CREDENTIALS) > $(TEMP_ENV)
 	@grep -Fvx -f $(TEMP_ENV) $(ENV_FILE) > $(ENV_FILE).tmp && mv $(ENV_FILE).tmp $(ENV_FILE)
 	@rm -f $(TEMP_ENV)
 
+ps		:
+	@echo "<<< Showing processes (ps aux) in all containers >>>"
+	@docker compose -f $(DC_FILE) config --services | xargs -I {} sh -c 'echo; \
+	echo "--------------------------------------------------"; \
+	echo "    --- Processes in Container: {} ---"; \
+	echo "--------------------------------------------------"; \
+	docker exec -t {} ps aux || echo "Error executing ps in {}"; \
+	echo "--------------------------------------------------";'
+	@echo
+
 down		:
-	docker compose -f ./srcs/docker-compose.yml down
+	docker compose -f $(DC_FILE) down
 
 fdown		:
 	@sudo rm -rf ~/data
-	docker compose -f ./srcs/docker-compose.yml down --rmi all -v
+	docker compose -f $(DC_FILE) down --rmi all -v
 
 prune		: fdown
 	docker system prune -a --volumes --force
 
 logs		:
-	docker compose -f ./srcs/docker-compose.yml logs
+	docker compose -f $(DC_FILE) logs
 
 re			: fdown up
 
 stop		:
-	docker compose -f ./srcs/docker-compose.yml stop
+	docker compose -f $(DC_FILE) stop
 
 .PHONY			: all up down fdown prune logs re stop
